// Generated by scripts/generate-config-schema.mjs from data/config-schema.json.
// Do not edit. Edit the schema and re-run the generator; `pixi run check-config-schema`
// fails the build when this file is stale.

#pragma once

#include <cstddef>
#include <string>

namespace cameraunlock {
namespace config_keys {

inline constexpr const char* kUdpPort = "udpport";
inline constexpr const char* kEnableOnStartup = "enableonstartup";
inline constexpr const char* kYawSensitivity = "yawsensitivity";
inline constexpr const char* kPitchSensitivity = "pitchsensitivity";
inline constexpr const char* kRollSensitivity = "rollsensitivity";
inline constexpr const char* kInvertYaw = "invertyaw";
inline constexpr const char* kInvertPitch = "invertpitch";
inline constexpr const char* kInvertRoll = "invertroll";
inline constexpr const char* kLocalSmoothing = "localsmoothing";
inline constexpr const char* kRemoteSmoothing = "remotesmoothing";
inline constexpr const char* kWorldSpaceYaw = "worldspaceyaw";
inline constexpr const char* kAimDecoupling = "aimdecoupling";
inline constexpr const char* kShowReticle = "showreticle";
inline constexpr const char* kReticleColor = "reticlecolor";
inline constexpr const char* kPositionEnabled = "positionenabled";
inline constexpr const char* kPositionSensitivityX = "positionsensitivityx";
inline constexpr const char* kPositionSensitivityY = "positionsensitivityy";
inline constexpr const char* kPositionSensitivityZ = "positionsensitivityz";
inline constexpr const char* kPositionLimitX = "positionlimitx";
inline constexpr const char* kPositionLimitY = "positionlimity";
inline constexpr const char* kPositionLimitYDown = "positionlimitydown";
inline constexpr const char* kPositionLimitZ = "positionlimitz";
inline constexpr const char* kPositionLimitZBack = "positionlimitzback";
inline constexpr const char* kInvertPositionX = "invertpositionx";
inline constexpr const char* kInvertPositionY = "invertpositiony";
inline constexpr const char* kInvertPositionZ = "invertpositionz";
inline constexpr const char* kTrackerPivotForward = "trackerpivotforward";
inline constexpr const char* kTrackerPivotUp = "trackerpivotup";
inline constexpr const char* kToggleKey = "togglekey";
inline constexpr const char* kPositionToggleKey = "positiontogglekey";
inline constexpr const char* kReticleToggleKey = "reticletogglekey";
inline constexpr const char* kCycleTrackingModeKey = "cycletrackingmodekey";
inline constexpr const char* kYawModeKey = "yawmodekey";
inline constexpr const char* kRecenterKey = "recenterkey";
inline constexpr const char* kAdsMode = "adsmode";
inline constexpr const char* kLightFollowsHead = "lightfollowshead";
inline constexpr const char* kLightMultiplier = "lightmultiplier";

inline constexpr const char* kSmoothing = "smoothing";

}  // namespace config_keys

/// One accepted spelling of a config key. `normalized` is the lookup form (lowercased,
/// '_' and '-' stripped); `canonical` is the name every spelling of the concept resolves
/// to, matching ConfigKeySchema.Keys on the C# side.
struct ConfigKeyAlias {
    const char* normalized;
    const char* canonical;
    bool retired;
};

inline constexpr ConfigKeyAlias kConfigKeyAliases[] = {
    { "adsmode", "adsmode", false },
    { "aimdecouple", "aimdecoupling", false },
    { "aimdecoupling", "aimdecoupling", false },
    { "autoenable", "enableonstartup", false },
    { "centerkey", "recenterkey", false },
    { "centrekey", "recenterkey", false },
    { "compensatecrosshair", "showreticle", false },
    { "compensateflashlight", "lightfollowshead", false },
    { "compensatereticle", "showreticle", false },
    { "crosshaircolor", "reticlecolor", false },
    { "crosshaircolour", "reticlecolor", false },
    { "crosshairtogglekey", "reticletogglekey", false },
    { "cyclemode", "cycletrackingmodekey", false },
    { "cyclemodekey", "cycletrackingmodekey", false },
    { "cycletrackingmode", "cycletrackingmodekey", false },
    { "cycletrackingmodekey", "cycletrackingmodekey", false },
    { "decoupleaim", "aimdecoupling", false },
    { "decoupledaim", "aimdecoupling", false },
    { "drawreticle", "showreticle", false },
    { "enable6dof", "positionenabled", false },
    { "enableaimdecoupling", "aimdecoupling", false },
    { "enableatstartup", "enableonstartup", false },
    { "enabledonstartup", "enableonstartup", false },
    { "enableheadtracking", "enableonstartup", false },
    { "enablekey", "togglekey", false },
    { "enableonstartup", "enableonstartup", false },
    { "enableposition", "positionenabled", false },
    { "enablepositiontracking", "positionenabled", false },
    { "flashlightfollowshead", "lightfollowshead", false },
    { "flashlightmultiplier", "lightmultiplier", false },
    { "flashlightscale", "lightmultiplier", false },
    { "horizonlock", "worldspaceyaw", false },
    { "horizonlockedyaw", "worldspaceyaw", false },
    { "invertpitch", "invertpitch", false },
    { "invertpitchaxis", "invertpitch", false },
    { "invertpositionx", "invertpositionx", false },
    { "invertpositiony", "invertpositiony", false },
    { "invertpositionz", "invertpositionz", false },
    { "invertroll", "invertroll", false },
    { "invertrollaxis", "invertroll", false },
    { "inverttrackerx", "invertpositionx", false },
    { "inverttrackery", "invertpositiony", false },
    { "inverttrackerz", "invertpositionz", false },
    { "invertx", "invertpositionx", false },
    { "inverty", "invertpositiony", false },
    { "invertyaw", "invertyaw", false },
    { "invertyawaxis", "invertyaw", false },
    { "invertz", "invertpositionz", false },
    { "keycyclemode", "cycletrackingmodekey", false },
    { "keytoggle", "togglekey", false },
    { "keyyawmode", "yawmodekey", false },
    { "lightfollowshead", "lightfollowshead", false },
    { "lightmultiplier", "lightmultiplier", false },
    { "limitdown", "positionlimitydown", false },
    { "limitx", "positionlimitx", false },
    { "limity", "positionlimity", false },
    { "limitydown", "positionlimitydown", false },
    { "limityup", "positionlimity", false },
    { "limitz", "positionlimitz", false },
    { "limitzback", "positionlimitzback", false },
    { "limitzbackward", "positionlimitzback", false },
    { "limitzforward", "positionlimitz", false },
    { "limitzfwd", "positionlimitz", false },
    { "listenport", "udpport", false },
    { "localsmoothing", "localsmoothing", false },
    { "lockhorizon", "worldspaceyaw", false },
    { "maxx", "positionlimitx", false },
    { "maxy", "positionlimity", false },
    { "maxydown", "positionlimitydown", false },
    { "maxz", "positionlimitz", false },
    { "maxzback", "positionlimitzback", false },
    { "modecycle", "cycletrackingmodekey", false },
    { "modekey", "cycletrackingmodekey", false },
    { "movecrosshair", "showreticle", false },
    { "neckmodelforward", "trackerpivotforward", false },
    { "neckmodelheight", "trackerpivotup", false },
    { "neckpivotforward", "trackerpivotforward", false },
    { "neckpivotup", "trackerpivotup", false },
    { "opentrackport", "udpport", false },
    { "pitchinvert", "invertpitch", false },
    { "pitchmultiplier", "pitchsensitivity", false },
    { "pitchscale", "pitchsensitivity", false },
    { "pitchsens", "pitchsensitivity", false },
    { "pitchsensitivity", "pitchsensitivity", false },
    { "pivotarm", "trackerpivotforward", false },
    { "pivotforward", "trackerpivotforward", false },
    { "pivotup", "trackerpivotup", false },
    { "port", "udpport", false },
    { "positionenabled", "positionenabled", false },
    { "positioninvertx", "invertpositionx", false },
    { "positioninverty", "invertpositiony", false },
    { "positioninvertz", "invertpositionz", false },
    { "positionkey", "positiontogglekey", false },
    { "positionlimitx", "positionlimitx", false },
    { "positionlimity", "positionlimity", false },
    { "positionlimitydown", "positionlimitydown", false },
    { "positionlimityup", "positionlimity", false },
    { "positionlimitz", "positionlimitz", false },
    { "positionlimitzback", "positionlimitzback", false },
    { "positionlimitzbackward", "positionlimitzback", false },
    { "positionlimitzforward", "positionlimitz", false },
    { "positionlimitzfwd", "positionlimitz", false },
    { "positionmaxx", "positionlimitx", false },
    { "positionmaxy", "positionlimity", false },
    { "positionmaxydown", "positionlimitydown", false },
    { "positionmaxz", "positionlimitz", false },
    { "positionmaxzback", "positionlimitzback", false },
    { "positionsensitivityx", "positionsensitivityx", false },
    { "positionsensitivityy", "positionsensitivityy", false },
    { "positionsensitivityz", "positionsensitivityz", false },
    { "positionsensx", "positionsensitivityx", false },
    { "positionsensy", "positionsensitivityy", false },
    { "positionsensz", "positionsensitivityz", false },
    { "positiontogglekey", "positiontogglekey", false },
    { "positiontracking", "positionenabled", false },
    { "positiontrackingenabled", "positionenabled", false },
    { "recenterkey", "recenterkey", false },
    { "recentrekey", "recenterkey", false },
    { "remotesmoothing", "remotesmoothing", false },
    { "reticlecolor", "reticlecolor", false },
    { "reticlecolour", "reticlecolor", false },
    { "reticleenabled", "showreticle", false },
    { "reticlekey", "reticletogglekey", false },
    { "reticletoggle", "reticletogglekey", false },
    { "reticletogglekey", "reticletogglekey", false },
    { "rollinvert", "invertroll", false },
    { "rollmultiplier", "rollsensitivity", false },
    { "rollscale", "rollsensitivity", false },
    { "rollsens", "rollsensitivity", false },
    { "rollsensitivity", "rollsensitivity", false },
    { "sensitivitypitch", "pitchsensitivity", false },
    { "sensitivityroll", "rollsensitivity", false },
    { "sensitivityx", "positionsensitivityx", false },
    { "sensitivityy", "positionsensitivityy", false },
    { "sensitivityyaw", "yawsensitivity", false },
    { "sensitivityz", "positionsensitivityz", false },
    { "sensx", "positionsensitivityx", false },
    { "sensy", "positionsensitivityy", false },
    { "sensz", "positionsensitivityz", false },
    { "showcrosshair", "showreticle", false },
    { "showdecoupledcrosshair", "showreticle", false },
    { "showdecoupledreticle", "showreticle", false },
    { "showreticle", "showreticle", false },
    { "sixdofenabled", "positionenabled", false },
    { "sixdoftogglekey", "positiontogglekey", false },
    { "smoothing", "smoothing", true },
    { "smoothingfactor", "smoothing", true },
    { "smoothinglocal", "localsmoothing", false },
    { "smoothingremote", "remotesmoothing", false },
    { "startenabled", "enableonstartup", false },
    { "toggle", "togglekey", false },
    { "togglecrosshairkey", "reticletogglekey", false },
    { "togglekey", "togglekey", false },
    { "togglepositionkey", "positiontogglekey", false },
    { "togglereticlekey", "reticletogglekey", false },
    { "toggletracking", "togglekey", false },
    { "toggletrackingkey", "togglekey", false },
    { "toggleyawkey", "yawmodekey", false },
    { "toggleyawmode", "yawmodekey", false },
    { "toggleyawmodekey", "yawmodekey", false },
    { "trackerpivot", "trackerpivotforward", false },
    { "trackerpivotforward", "trackerpivotforward", false },
    { "trackerpivotup", "trackerpivotup", false },
    { "trackingmodekey", "cycletrackingmodekey", false },
    { "trackingport", "udpport", false },
    { "trackingtogglekey", "togglekey", false },
    { "udpport", "udpport", false },
    { "worldlockedyaw", "worldspaceyaw", false },
    { "worldspaceyaw", "worldspaceyaw", false },
    { "worldyaw", "worldspaceyaw", false },
    { "worldyawkey", "yawmodekey", false },
    { "xsensitivity", "positionsensitivityx", false },
    { "yawinvert", "invertyaw", false },
    { "yawmode", "yawmodekey", false },
    { "yawmodekey", "yawmodekey", false },
    { "yawmultiplier", "yawsensitivity", false },
    { "yawscale", "yawsensitivity", false },
    { "yawsens", "yawsensitivity", false },
    { "yawsensitivity", "yawsensitivity", false },
    { "ysensitivity", "positionsensitivityy", false },
    { "zsensitivity", "positionsensitivityz", false },
};

inline constexpr size_t kConfigKeyAliasCount = sizeof(kConfigKeyAliases) / sizeof(kConfigKeyAliases[0]);

/// Lowercases a key and strips '_' and '-'. Applied to both sides of a lookup.
inline std::string NormalizeConfigKey(const std::string& key) {
    std::string out;
    out.reserve(key.size());
    for (char c : key) {
        if (c == '_' || c == '-') continue;
        if (c >= 'A' && c <= 'Z') c = static_cast<char>(c - 'A' + 'a');
        out.push_back(c);
    }
    return out;
}

/// Resolves any accepted spelling to its canonical normalized name, or nullptr when the
/// key belongs to no concept in the schema. The returned pointer is static storage.
inline const char* ResolveConfigKey(const std::string& key) {
    const std::string normalized = NormalizeConfigKey(key);
    for (size_t i = 0; i < kConfigKeyAliasCount; ++i) {
        if (normalized == kConfigKeyAliases[i].normalized) return kConfigKeyAliases[i].canonical;
    }
    return nullptr;
}

/// True when the canonical name names a retired concept: it parses, and is ignored.
inline bool IsRetiredConfigKey(const char* canonical_key) {
    if (canonical_key == nullptr) return false;
    for (size_t i = 0; i < kConfigKeyAliasCount; ++i) {
        if (kConfigKeyAliases[i].retired && std::string(canonical_key) == kConfigKeyAliases[i].canonical) {
            return true;
        }
    }
    return false;
}

}  // namespace cameraunlock
